services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: tuusuario
      - key: N8N_BASIC_AUTH_PASSWORD
        value: tupasswordsegura
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_EDITOR_BASE_URL
        value: https://tudominio.onrender.com
      - key: GENERIC_TIMEZONE
        value: America/Mexico_City
